image: gradle:8-jdk17-alpine

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - chmod a+x gradlew

stages:
  - build
  - verify
  - deploy

build:
  stage: build
  script:
    - ./gradlew assemble
  artifacts:
    paths:
      - build/libs/*.jar

junit:
  stage: verify
  dependencies:
    - build
  script:
    - ./gradlew test
  coverage: '/    - Instruction Coverage: ([0-9.]+)%/'
  artifacts:
    reports:
      junit: build/test-results/test/**.xml

publish:
  stage: deploy
  script:
    - ./gradlew clean
    - ./gradlew publish
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: manual
    - when: never

jar:
  stage: deploy
  script:
    - ./gradlew build
  artifacts:
    paths:
      - build/libs/*.jar
  when: manual

badges:
  stage: deploy
  script:
    - apt-get -qq update
    - apt-get -qq install python3 python3-pip --yes
    - pip3 install anybadge
    - ./gradlew build -q
    - anybadge -l spigot -v "$(./gradlew spigotVersion -q)" -f spigot.svg -c "#007ec6"
    - anybadge -l atsArguments -v "$(./gradlew argumentsVersion -q)" -f arguments.svg -c "#007ec6"
  artifacts:
    paths:
      - spigot.svg
      - arguments.svg
    when: always
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: manual
    - when: never

pages:
  stage: deploy
  dependencies:
    - junit
  script:
    - mv build/reports/jacoco/test/html/ public/
  artifacts:
    paths:
      - public/**
  only:
    - master
  when: manual
