plugins {
	id 'org.barfuin.gradle.jacocolog' version '3.1.0'
	id 'com.github.johnrengelman.shadow' version '8.1.1'
	id 'kr.entree.spigradle' version '2.4.3'
}

apply plugin: 'idea'
apply plugin: 'java'
apply plugin: 'jacoco'
apply plugin: 'maven-publish'

sourceCompatibility = JavaVersion.VERSION_17
targetCompatibility = JavaVersion.VERSION_17

repositories {
	mavenCentral()
	mavenLocal()
	spigot()
	maven { url 'https://gitlab.com/api/v4/projects/12063927/packages/maven' }
}

dependencies {
	compileOnly group: 'org.spigotmc', name: 'spigot-api', version: "${spigotVersion}-R0.1-SNAPSHOT"
	compileOnly group: 'org.jetbrains', name: 'annotations', version: '24.0.1'
	implementation group: 'eu.andret', name: 'ats-arguments', version: argumentsVersion
	implementation group: 'org.bstats', name: 'bstats-bukkit', version: '3.0.2'

	testCompileOnly group: 'org.jetbrains', name: 'annotations', version: '24.0.1'
	testImplementation group: 'org.assertj', name: 'assertj-core', version: '3.24.2'
	testImplementation group: 'org.mockito', name: 'mockito-core', version: '5.3.1'
	testImplementation group: 'org.spigotmc', name: 'spigot-api', version: "${spigotVersion}-R0.1-SNAPSHOT"
	testImplementation group: 'org.testng', name: 'testng', version: '7.8.0'
}

compileJava.options.compilerArgs << '-parameters' << '-g' << '-Xlint:deprecation' << '-Xlint:unchecked'
compileTestJava.options.compilerArgs << '-parameters' << '-g' << '-Xlint:deprecation' << '-Xlint:unchecked'

spigot {
	authors = ['Andret']
	apiVersion = '1.17'
	description = 'A plugin that allows to craft the blocks, that are generating other blocks.'
	version = project.version
	website = 'https://www.spigotmc.org/resources/ats-andret-tools-system-block-generator-craft-infinite-block-generator.96216/'
	libraries = ['org.jetbrains:annotations:24.0.1']

	//noinspection GroovyAssignabilityCheck
	commands {
		blockgenerator {
			aliases = ['bg', 'generator']
		}
	}

	//noinspection GroovyAssignabilityCheck
	permissions {
		'ats.blockgenerator.*' {
			children = ['ats.blockgenerator.get': true]
		}
	}
}

test {
	useTestNG()
	finalizedBy jacocoTestCoverageVerification, jacocoAggregatedReport
}

jacocoTestReport {
	afterEvaluate {
		classDirectories.setFrom(files(classDirectories.files.collect {
			fileTree(dir: it, exclude: ['**/*Plugin.class'])
		}))
	}
}

jacocoTestCoverageVerification {
	violationRules {
		rule {
			limit {
				minimum = 0.8
			}
		}
	}

	afterEvaluate {
		classDirectories.setFrom(files(classDirectories.files.collect {
			fileTree(dir: it, exclude: ['**/*Plugin.*'])
		}))
	}
}

javadoc {
	source = sourceSets.main.allJava
	classpath = configurations.compileClasspath

	options {
		memberLevel = JavadocMemberLevel.PUBLIC
		author = true
		links = ['https://docs.oracle.com/en/java/javase/17/docs/api/']
	}
}

task sourceJar(type: Jar) {
	archiveClassifier.set('sources')
	from sourceSets.main.allJava
}

task packageJavadoc(type: Jar) {
	archiveClassifier.set('javadoc')
	from javadoc
}

publishing {
	publications {
		//noinspection GroovyAssignabilityCheck
		library(MavenPublication) {
			from components.java
			artifact tasks.sourceJar
			artifact tasks.packageJavadoc
			groupId = project.group
			version = project.version
			artifactId = project.artifact
		}
	}
	repositories {
		maven {
			url 'https://gitlab.com/api/v4/projects/6382356/packages/maven'
			//noinspection GroovyAssignabilityCheck
			credentials(HttpHeaderCredentials) {
				name = 'Job-Token'
				value = System.getenv('CI_JOB_TOKEN')
			}
			authentication {
				//noinspection GroovyAssignabilityCheck
				header(HttpHeaderAuthentication)
			}
		}
	}
}

shadowJar {
	archiveFileName = "${project.name}-${project.version}.jar"
	relocate 'eu.andret.arguments', 'eu.andret.ats.blockgenerator.arguments'
	relocate 'org.bstats', 'eu.andret.ats.blockgenerator.bstats'
}

build.dependsOn(shadowJar)
