plugins {
    id "ru.endlesscode.bukkitgradle" version "0.8.0"
}

group = pluginGroup
version = pluginVersion
description = pluginDescription

sourceCompatibility = 1.8
targetCompatibility = 1.8

jar {
    baseName = pluginName
    version = pluginVersion
}

dependencies {
    compile group: 'org.slf4j', name: 'slf4j-simple', version: '1.6.1'
    compileOnly spigotApi()
    compileOnly 'org.projectlombok:lombok:1.16.20'
}
