generators:
  - delay: 1
    name: 'sponge'
    items:
      generator:
        material: SPONGE
        name: '&5Creates stone!'
        lore:
          - 'I will give you'
          - '&4MANY&r cobblestone blocks!'
      generated:
        material: STONE
        name: 'Generated stone XD'
        lore:
          - 'Yay, I was generated!'
          - 'Either do I, hm...'
    crafting:
      shape:
        - 'SSS'
        - 'SPS'
        - 'S S'
      mapping:
        'S': STONE
        'P': PISTON
  - delay: 10
    name: 'dirt'
    items:
      generator:
        material: DIRT
        name: '&5Creates OBSIDIAN!'
        lore:
          - 'HIT ME!!'
      generated:
        material: OBSIDIAN
    crafting:
      shape:
        - 'S S'
        - 'SOS'
        - 'SSS'
      mapping:
        'S': STONE
        'O': OBSIDIAN
