name: BlockGens
main: eu.andret.blockgens.BlockGensPlugin
version: ${version}
author: Andret
api-version: '26.2'
description: Craftable generator blocks that keep generating a configured block above themselves.
website: https://github.com/andret2344/block-gens

permissions:
  blockgens.*:
    description: Grants access to all BlockGens commands.
    children:
      blockgens.get: true
      blockgens.give: true
      blockgens.reload: true
  blockgens.get:
    description: Allows to get generator blocks, generated blocks and drop items with the command.
    default: op
  blockgens.give:
    description: Allows to give generator blocks to other players with the command.
    default: op
  blockgens.reload:
    description: Allows to reload the config.
    default: op
